#!/bin/bash

window=$1
rice_name=$2
widget_name=$3


eww -c ~/.config/qtile/widgets/$rice_name/$widget_name open $widget_name --toggle --screen $window
# sleep 10
# eww -c ~/.config/qtile/widgets/$rice_name/$widget_name open $widget_name --toggle --screen $window
