#!/usr/bin/env bash

# if you want the same wallpaper for each monitor
#
output=$(xrandr)
connected_monitors=$(echo "$output" | grep -E " connected ")
num_monitors=$(echo "$connected_monitors" | wc -l)
# qdir="$HOME/code/qtile"
qdir="$HOME/.config/qtile"

theme_name=$(cat "$qdir"/theme/theme_name.txt)


for ((i=0; i<$num_monitors; i++))
do
  # nitrogen --head=$i --set-zoom-fill "$qdir"/wallpapers/"$theme_name".jpg
  nitrogen --head=$i --set-zoom-fill ~/Downloads/wallpaper.jpg
done

# if uou want a wallpaper fill it:
# nitrogen --set-zoom-fill ~/.dotfiles/.wallpaper/dragon.jpg
