#!/bin/bash


status=$(playerctl status 2>/dev/null)

playing=false

if [[ "$status" == "Playing" ]]; then
  playing=true
elif [[ "$status" == "Paused" ]]; then
  playing=false
else 
  playing=false
fi

echo $playing
