#!/bin/bash

input_string=$2

declare -a words_array

OLD_IFS=$IFS

IFS=' '

read -ra words_array <<< "$input_string"

browse () {
  if ps -A | grep -q "firefox"; then
    xdg-open $1
  else
    nohup firefox >/dev/null 2>&1 &
    sleep 2
    xdg-open $1
  fi
}

status=$(playerctl status 2>/dev/null)


if [[ "$status" == "Playing" ]]; then
  playerctl play-pause
elif [[ "$status" == "Paused" ]]; then
  playerctl play-pause
else
  spotify="https://open.spotify.com/search/"


  browser_title="firefox"

  # Check if the browser is running
  if pgrep -x "$(basename "$browser_title")" > /dev/null; then
      # Check if the Spotify tab is open by searching for its title in the browser
      if xdotool search --name "$browser_title" search --name "Spotify"; then
          notify-send 'music player' "please play one of your favorite song."
      else
          browse "$spotify"
      fi
  else
      browse "$spotify"
  fi
fi
