#!/bin/bash
#
eww="$HOME/.config/eww/target/release/eww"
widget_dir="$HOME/.config/qtile/widgets/dashboard"

$eww -c "$widget_dir/column_a" open column_a --toggle --screen "$1" &
$eww -c "$widget_dir/column_b" open column_b --toggle --screen "$1" &
# eww -c "$widget_dir/column_c" open column_c --toggle --screen "$1"
