#!/bin/bash
#
EWW_DIR="$HOME/.config/qtile/widgets/dashboard"

eww -c "$EWW_DIR/column_a" open column_a --toggle --screen "$1" &
eww -c "$EWW_DIR/column_b" open column_b --toggle --screen "$1" &
# eww -c "$EWW_DIR/column_c" open column_c --toggle --screen "$1"
