#!/bin/bash
#
# firefox_pid=$(pgrep firefox)
# nvim_pid=$(pgrep vim)
#
# if [ -n "$firefox_pid" ]; then
#     rss=$(ps -o rss= -p $firefox_pid)
#
#     rss_mb=$(echo "scale=2; $rss / 1024" | bc)
#
#     echo "Memory usage for firefox: ${rss_mb} MB"
# fi

case "$1" in
  --kitty)
    kitty_pids=($(pgrep kitty))
    total_memory=0
    for pid in "${kitty_pids[@]}"; do
        rss=$(ps -o rss= -p $pid)
        rss_mb=$(echo "scale=2; $rss / 1024" | bc)
        total_memory=$(echo "$total_memory + $rss" | bc)
    done
    total_memory_mb=$(echo "scale=2; $total_memory / 1024" | bc)
    echo "${total_memory_mb} MB"
    ;;
  --vim)
    vim_pids=($(pgrep vim))
    total_memory=0
    for pid in "${vim_pids[@]}"; do
        rss=$(ps -o rss= -p $pid)
        rss_mb=$(echo "scale=2; $rss / 1024" | bc)
        total_memory=$(echo "$total_memory + $rss" | bc)
    done
    total_memory_mb=$(echo "scale=2; $total_memory / 1024" | bc)
    echo "${total_memory_mb} MB"
    ;;
  --firefox)
    firefox_pids=($(pgrep firefox))
    total_memory=0
    for pid in "${firefox_pids[@]}"; do
        rss=$(ps -o rss= -p $pid)
        rss_mb=$(echo "scale=2; $rss / 1024" | bc)
        total_memory=$(echo "$total_memory + $rss" | bc)
    done
    total_memory_mb=$(echo "scale=2; $total_memory / 1024" | bc)
    echo "${total_memory_mb} MB"
    ;;
  *)
    ;;
esac

