require("configs.plugins-setup")
require("configs.core.options")
require("configs.core.keymaps")
require("configs.core.colorscheme")
require("configs.plugins.vim-tree")
require("configs.plugins.airline")
require("configs.plugins.telescope")
require("configs.plugins.nvim-cmp")
require("configs.plugins.lsp.mason")
require("configs.plugins.lsp.lspsaga")
require("configs.plugins.lsp.lspconfig")
require("configs.plugins.lsp.null-ls")
require("configs.plugins.autopairs")
require("configs.plugins.treesitter")
require("configs.plugins.gitsigns")
-- material configs
-- require("configs.core.themes-configs.material")
