#!/bin/bash


case "$1" in
  --wall)
    current_num_wall=$(cat "$HOME/.config/qtile/wallpapers/num_wallpaper.txt")

    wall="$HOME/.config/qtile/wallpapers/$current_num_wall.jpg"
    echo -n "$wall"
    ;;
  --next)
    ~/.config/qtile/scripts/set_wallpaper --next
    ;;
  --prev)
    ~/.config/qtile/scripts/set_wallpaper --prev
    ;;
  *)
    ;;
esac
echo
