#!/bin/bash

case "$1" in
  --title)
      title=$(playerctl metadata spotify --format "{{ title }}" 2>/dev/null)
      if [[ -z "$title" ]]; then
        echo -n "No Title"
      else
        echo -n "$title"
      fi
    ;;
  --album)
      title=$(playerctl metadata spotify --format "{{ album }}" 2>/dev/null)
      if [[ -z "$title" ]]; then
        echo -n "Unknown"
      else
        echo -n "$title"
      fi
    ;;
  --artist)
      title=$(playerctl metadata spotify --format "{{ artist }}" 2>/dev/null)
      if [[ -z "$title" ]]; then
        echo -n "Unknown"
      else
        echo -n "$title"
      fi
    ;;
  --artUrl)
    artUrl=$(playerctl metadata | awk '/mpris:artUrl/ {print $3}') 
      if [[ -z "$artUrl" ]]; then
        echo -n "$HOME/.config/qtile/widgets/music-player/assets/artImg_not_found.jpg"
      else
        echo -n "$artUrl"
      fi
    ;;
  *)
  ;;
esac

# Add a newline character at the end
echo

