#!/bin/bash

zscroll -l 30 \
        --delay 0.1 \
        --scroll-padding "  " \
        --match-command "playerctl metadata spotify --format '{{ title }} - {{ artist }}'" \
        --match-text "Playing" "--scroll 1" \
        --match-text "Paused" "--scroll 0" \
        --update-check true "playerctl metadata spotify --format '{{ title }} - {{ artist }}'"
